/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2024-12-11 13:04:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class sign_002dup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Sign-up</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/RegisterServlet\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div style=\"width: 100%; height: 100%; position: relative; background: white\">\r\n");
      out.write("        <div style=\"left: 24.89px; top: 14.50px; position: absolute\">\r\n");
      out.write("            <div style=\"width: 30px; height: 17px; left: 0px; top: 0px; position: absolute; text-align: center; color: #1E1E2D; font-size: 15px; font-family: SF Pro Display; font-weight: 600; line-height: 18px; word-wrap: break-word\">9:41</div>\r\n");
      out.write("            <div style=\"width: 67px; height: 11.50px; left: 273.61px; top: 2.50px; position: absolute\">\r\n");
      out.write("                <div style=\"width: 24.50px; height: 11.50px; left: 42.50px; top: 0px; position: absolute\">\r\n");
      out.write("                    <div style=\"width: 24.50px; height: 11.50px; left: 0px; top: 0px; position: absolute; background: #A2A2A7; border: 1px solid;\"></div>\r\n");
      out.write("                    <div style=\"width: 18px; height: 7.67px; left: 2px; top: 1.92px; position: absolute; background: #1E1E2D; border-radius: 1.60px; border: 1px solid;\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div style=\"width: 17.10px; height: 10.70px; left: 0px; top: 0.44px; position: absolute; background: #1E1E2D; border: 1px solid;\"></div>\r\n");
      out.write("                <div style=\"width: 15.40px; height: 11.06px; left: 22.10px; top: 0.24px; position: absolute; background: #1E1E2D; border: 1px solid;\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div style=\"width: 335px; left: 20px; top: 221px; position: absolute\">\r\n");
      out.write("            <label style=\"color: #A2A2A7; font-size: 14px; font-family: Poppins; font-weight: 400; line-height: 14px;\">이름</label>\r\n");
      out.write("            <input type=\"text\" name=\"username\" style=\"width: 335px; height: 32px; border: 1.5px solid #F4F4F4; margin-top: 8px;\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div style=\"width: 335px; left: 20px; top: 305px; position: absolute\">\r\n");
      out.write("            <label style=\"color: #A2A2A7; font-size: 14px; font-family: Poppins; font-weight: 400; line-height: 14px;\">이메일</label>\r\n");
      out.write("            <input type=\"email\" name=\"email\" style=\"width: 335px; height: 32px; border: 1.5px solid #F4F4F4; margin-top: 8px;\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div style=\"width: 335px; left: 20px; top: 389px; position: absolute\">\r\n");
      out.write("            <label style=\"color: #A2A2A7; font-size: 14px; font-family: Poppins; font-weight: 400; line-height: 14px;\">비밀번호</label>\r\n");
      out.write("            <input type=\"password\" name=\"password\" style=\"width: 335px; height: 32px; border: 1.5px solid #F4F4F4; margin-top: 8px;\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div style=\"width: 335px; height: 56px; left: 20px; top: 576px; position: absolute;\">\r\n");
      out.write("            <button type=\"submit\" style=\"width: 335px; height: 56px; background: #0066FF; color: white; font-size: 16px; font-family: Poppins; font-weight: 600; line-height: 24px; border: none; border-radius: 16px; cursor: pointer;\">\r\n");
      out.write("                등록하기\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div style=\"width: 122px; height: 16px; left: 127px; top: 662px; position: absolute; color: #0066FF; font-size: 14px; font-family: Poppins; font-weight: 500; line-height: 14px; text-align: center; cursor: pointer;\"\r\n");
      out.write("             onclick=\"location.href='sign-in.jsp';\">\r\n");
      out.write("            이미 계정이 있어요\r\n");
      out.write("        </div>\r\n");
      out.write("        <div style=\"width: 123px; height: 34px; left: 20px; top: 149px; position: absolute; color: #1E1E2D; font-size: 32px; font-family: Poppins; font-weight: 500; line-height: 32px; word-wrap: break-word;\">\r\n");
      out.write("            회원가입\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
