/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2024-12-01 03:05:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class deposit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>입금하기</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            background: white;\r\n");
      out.write("            font-family: 'Poppins', sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <form action=\"processDeposit.jsp\" method=\"POST\" style=\"width: 100%; height: 100%; position: relative; background: white;\">\r\n");
      out.write("        <div style=\"left: 24.89px; top: 14.50px; position: absolute;\">\r\n");
      out.write("            <div style=\"width: 30px; height: 17px; left: 0px; top: 0px; position: absolute; text-align: center; color: #1E1E2D; font-size: 15px; font-family: SF Pro Display; font-weight: 600; line-height: 18px; word-wrap: break-word;\">9:41</div>\r\n");
      out.write("            <div style=\"width: 67px; height: 11.50px; left: 273.61px; top: 2.50px; position: absolute;\">\r\n");
      out.write("                <div style=\"width: 24.50px; height: 11.50px; left: 42.50px; top: 0px; position: absolute;\">\r\n");
      out.write("                    <div style=\"width: 24.50px; height: 11.50px; left: 0px; top: 0px; position: absolute; background: #A2A2A7; border: 1px solid;\"></div>\r\n");
      out.write("                    <div style=\"width: 18px; height: 7.67px; left: 2px; top: 1.92px; position: absolute; background: #1E1E2D; border-radius: 1.60px; border: 1px solid;\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div style=\"width: 17.10px; height: 10.70px; left: 0px; top: 0.44px; position: absolute; background: #1E1E2D; border: 1px solid;\"></div>\r\n");
      out.write("                <div style=\"width: 15.40px; height: 11.06px; left: 22.10px; top: 0.24px; position: absolute; background: #1E1E2D; border: 1px solid;\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div style=\"width: 237px; left: 20px; top: 54px; position: absolute;\">\r\n");
      out.write("            <div style=\"width: 42px; height: 42px; left: 0px; top: 0px; position: absolute;\">\r\n");
      out.write("                <div style=\"width: 42px; height: 42px; left: 0px; top: 0px; position: absolute; background: #F4F4F4; border-radius: 9999px; border: 1px solid;\"></div>\r\n");
      out.write("                <div style=\"width: 20px; height: 20px; left: 11px; top: 11px; position: absolute;\">\r\n");
      out.write("                    <div style=\"width: 6px; height: 12px; left: 7px; top: 4px; position: absolute; border: 1.50px #1E1E2D solid;\"></div>\r\n");
      out.write("                    <div style=\"width: 20px; height: 20px; left: 0px; top: 0px; position: absolute; border: 1px solid;\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div style=\"width: 140px; height: 20px; left: 97px; top: 11px; position: absolute; text-align: center; color: #1E1E2D; font-size: 18px; font-family: Poppins; font-weight: 500; line-height: 18px; word-wrap: break-word;\">입금하기</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div style=\"width: 335px; height: 56px; left: 20px; top: 706px; position: absolute;\">\r\n");
      out.write("            <button type=\"submit\" style=\"width: 335px; height: 56px; left: 0px; top: 0px; position: absolute; background: #0066FF; border-radius: 16px; border: 1px solid; color: white; font-size: 16px; font-family: Poppins; font-weight: 600; line-height: 24px; text-align: center;\">입금하기</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div style=\"width: 345px; height: 116px; left: 10px; top: 312px; position: absolute;\">\r\n");
      out.write("            <div style=\"width: 335px; height: 116px; left: 10px; top: 0px; position: absolute; background: white; border-radius: 14px; border: 1px #E7EAEE solid;\"></div>\r\n");
      out.write("            <div style=\"width: 148px; height: 49px; left: 20px; top: 35px; position: absolute;\">\r\n");
      out.write("                <label for=\"amount\" style=\"width: 102px; height: 13px; left: 0px; top: 0px; position: absolute; text-align: center; color: #7E848D; font-size: 11px; font-family: Poppins; font-weight: 400; line-height: 11px;\">금액</label>\r\n");
      out.write("                <input type=\"text\" id=\"amount\" name=\"amount\" style=\"width: 104px; height: 26px; left: 44px; top: 23px; position: absolute; opacity: 0.90; font-size: 24px; font-family: Poppins; font-weight: 600; text-align: center;\" placeholder=\"100000\" />\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div style=\"width: 335px; left: 20px; top: 127px; position: absolute;\">\r\n");
      out.write("            <label for=\"depositor\" style=\"width: 86px; height: 16px; left: 0px; top: 0px; position: absolute; color: #A2A2A7; font-size: 14px; font-family: Poppins; font-weight: 400; line-height: 14px;\">입금자명</label>\r\n");
      out.write("            <input type=\"text\" id=\"depositor\" name=\"depositor\" style=\"width: 335px; height: 32px; left: 0px; top: 31px; position: absolute; font-size: 14px; font-family: Poppins; color: #1E1E2D;\" value=\"Tanya Myroniuk\" />\r\n");
      out.write("        </div>\r\n");
      out.write("        <div style=\"width: 335px; left: 20px; top: 218px; position: absolute;\">\r\n");
      out.write("            <label for=\"description\" style=\"width: 79px; height: 16px; left: 0px; top: 0px; position: absolute; color: #A2A2A7; font-size: 14px; font-family: Poppins; font-weight: 400; line-height: 14px;\">Description</label>\r\n");
      out.write("            <input type=\"text\" id=\"description\" name=\"description\" style=\"width: 335px; height: 32px; left: 0px; top: 31px; position: absolute; font-size: 14px; font-family: Poppins; color: #1E1E2D;\" />\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
